### ISSUE TITLE
Request to Cite Our Software in Your Recent Publication

### ISSUE THREAD

**Issue by Sikerdebaard** [kaapana/kaapana#19]
I recently came across Kaapana and its related research papers, and I noticed that you used our software dcmrtstruct2nii but didn't cite it. We put a lot of effort into creating and maintaining this software to assist the research community, and proper citation helps support our work and give credit where it's due.

Could you please update your papers to include the following citation:

`Thomas Phil, Thomas Albrecht, Skylar Gay, & Mathis Ersted Rasmussen. (2023). Sikerdebaard/dcmrtstruct2nii: dcmrtstruct2nii v5 (Version v5). Zenodo. https://doi.org/10.5281/zenodo.4037864`

Thanks!

**Comment by Sikerdebaard** [comment]
Bump @jonasscherer @klauskades @markusbujotzek @unalakunal 

Please do not ignore citations.

**Comment by unalakunal** [comment]
Hi @Sikerdebaard , thanks for reaching out to us about this. We already added it in the [develop branch](https://github.com/kaapana/kaapana/blob/develop/.zenodo.json#L99) and it will be rolled out with our next release

**Comment by unalakunal** [comment]
@Sikerdebaard closing the issue, it is already added in our latest [0.3.0 release](https://github.com/kaapana/kaapana/blob/0.3.0/.zenodo.json#L101) as well

**Comment by Sikerdebaard** [comment]
@unalakunal thanks!
